### ISSUE TITLE
DMD won't compile on FreeBSD

### ISSUE THREAD

**Issue by whisperzer0** [opendlang/opend#94]
FreeBSD 15 
gcc 13.3.0
ldc2-1.140

When trying to follow the steps on the website to compile from source.
Step: make -j8 dmd  causes gmake to throw the following error:

```
Targets: 
 -> /tmp/opend/generated/freebsd/release/64/backend.o

Command: /forest/fox/dlang/ldc-1.40.0/bin/ldmd2 -c -of/tmp/opend/generated/freebsd/release/64/backend.o -w -de -fPIC -m64 -J/tmp/opend/generated/freebsd/release/64 -I/tmp/opend/compiler/src -g -color=on src/dmd/backend/backend.d src/dmd/backend/bcomplex.d src/dmd/backend/evalu8.d src/dmd/backend/divcoeff.d src/dmd/backend/dvec.d src/dmd/backend/go.d src/dmd/backend/gsroa.d src/dmd/backend/glocal.d src/dmd/backend/gdag.d src/dmd/backend/gother.d src/dmd/backend/gflow.d src/dmd/backend/dout.d src/dmd/backend/inliner.d src/dmd/backend/gloop.d src/dmd/backend/compress.d src/dmd/backend/cgelem.d src/dmd/backend/cgcs.d src/dmd/backend/ee.d src/dmd/backend/cod4.d src/dmd/backend/cod5.d src/dmd/backend/eh.d src/dmd/backend/nteh.d src/dmd/backend/blockopt.d src/dmd/backend/mem.d src/dmd/backend/cg.d src/dmd/backend/cgreg.d src/dmd/backend/dtype.d src/dmd/backend/debugprint.d src/dmd/backend/fp.d src/dmd/backend/symbol.d src/dmd/backend/symtab.d src/dmd/backend/elem.d src/dmd/backend/dcode.d src/dmd/backend/cgsched.d src/dmd/backend/cg87.d src/dmd/backend/cgxmm.d src/dmd/backend/cgcod.d src/dmd/backend/cod1.d src/dmd/backend/cod2.d src/dmd/backend/cod3.d src/dmd/backend/cv8.d src/dmd/backend/dcgcv.d src/dmd/backend/pdata.d src/dmd/backend/util2.d src/dmd/backend/var.d src/dmd/backend/md5.d src/dmd/backend/backconfig.d src/dmd/backend/drtlsym.d src/dmd/backend/dwarfeh.d src/dmd/backend/ptrntab.d src/dmd/backend/dvarstats.d src/dmd/backend/dwarfdbginf.d src/dmd/backend/cgen.d src/dmd/backend/goh.d src/dmd/backend/barray.d src/dmd/backend/cgcse.d src/dmd/backend/elpicpie.d src/dmd/backend/machobj.d src/dmd/backend/elfobj.d src/dmd/backend/mscoffobj.d src/dmd/backend/filespec.d src/dmd/backend/cgobj.d src/dmd/backend/aarray.d src/dmd/backend/disasm86.d

-----------------------------------------------------------
src/dmd/backend/cod1.d(1185): Error: `goto` skips declaration of variable `dmd.backend.cod1.getlvalue.idxregs`
src/dmd/backend/cod1.d(1192):        declared here

gmake: *** [Makefile:83: dmd] Error 1
```

**Comment by adamdruppe** [comment]
probably an easy fix, sounds like it just needs a var declaration moved to top of function in a freebsd block, but to test myself i gotta make a bsd thing.... well i have freebsd 12 i think upstairs i could try that. or maybe cross compile it from my linux box

also maybe i can send a PR to you to pull and test.

ill get back to you in a bit

**Comment by adamdruppe** [comment]
hmmm my cross compile worked. maybe upstream changed something in the new version of that host compiler.... yup that's it, it works in upstream 1.36, not in upstream 1.40. they're always breaking code upstream, ugh. but yeah

in any case i cross compiled dmd with ldc 1.40 and then cross compiled druntime with opend ldc and it worked with this patch:
https://github.com/opendlang/opend/commit/224240dcca1825fdea3c40877f20c8ee5d3d22e2

wanna try it?

**Comment by adamdruppe** [comment]
well actually i did freebsd 14 and you said 15 but that might not matter. druntime does have some version stuff like

```
// https://svnweb.freebsd.org/base/head/sys/sys/param.h?view=markup
// __FreeBSD_version numbers are documented in the Porter's Handbook.
// NOTE: When adding newer versions of FreeBSD, verify all current versioned
// bindings are still compatible with the release.

     version (FreeBSD_14) enum __FreeBSD_version = 1400000;
else version (FreeBSD_13) enum __FreeBSD_version = 1301000;
else version (FreeBSD_12) enum __FreeBSD_version = 1203000;
else version (FreeBSD_11) enum __FreeBSD_version = 1104000;
else version (FreeBSD_10) enum __FreeBSD_version = 1004000;
else version (FreeBSD_9)  enum __FreeBSD_version = 903000;
else version (FreeBSD_8)  enum __FreeBSD_version = 804000;
else static assert(false, "Unsupported version of FreeBSD");
```

but checking that reference link i don't see anything for 15 there either so idk.

we could possibly just lie and say it is 14 anyway.

**Comment by whisperzer0** [comment]
FreeBSD 15 is the bleeding edge build, so I don't expect there to be an registered release as it's technically testing release.
Unfortunately, it fixed that error but now getting compile errors of:

```
rc/dmd/cppmangle.d(2183): Deprecation: cast from `dmd.rootobject.RootObject` to `dmd.dsymbol.Dsymbol` not allowed in safe code
src/dmd/cppmangle.d(2183):        No dynamic type information for extern(C++) classes
src/dmd/cppmangle.d(2185): Deprecation: cast from `dmd.rootobject.RootObject` to `dmd.dsymbol.Dsymbol` not allowed in safe code
src/dmd/cppmangle.d(2185):        No dynamic type information for extern(C++) classes
src/dmd/cppmangle.d(2192): Deprecation: cast from `dmd.rootobject.RootObject` to `dmd.mtype.Type` not allowed in safe code
src/dmd/cppmangle.d(2192):        No dynamic type information for extern(C++) classes
src/dmd/doc.d(2620): Deprecation: cast from `dmd.mtype.Type` to `dmd.mtype.TypeFunction` not allowed in safe code
src/dmd/doc.d(2620):        No dynamic type information for extern(C++) classes
src/dmd/dtemplate.d(101): Deprecation: cast from `inout(RootObject)` to `inout(Expression)` not allowed in safe code
src/dmd/dtemplate.d(101):        No dynamic type information for extern(C++) classes
src/dmd/dtemplate.d(109): Deprecation: cast from `inout(RootObject)` to `inout(Dsymbol)` not allowed in safe code
src/dmd/dtemplate.d(109):        No dynamic type information for extern(C++) classes
src/dmd/dtemplate.d(117): Deprecation: cast from `inout(RootObject)` to `inout(Type)` not allowed in safe code
src/dmd/dtemplate.d(117):        No dynamic type information for extern(C++) classes
src/dmd/dtemplate.d(125): Deprecation: cast from `inout(RootObject)` to `inout(Tuple)` not allowed in safe code
src/dmd/dtemplate.d(125):        No dynamic type information for extern(C++) classes
src/dmd/dtemplate.d(133): Deprecation: cast from `inout(RootObject)` to `inout(Parameter)` not allowed in safe code
src/dmd/dtemplate.d(133):        No dynamic type information for extern(C++) classes
src/dmd/dtemplate.d(140): Deprecation: cast from `inout(RootObject)` to `inout(TemplateParameter)` not allowed in safe code
src/dmd/dtemplate.d(140):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(470): Deprecation: cast from `dmd.expression.Expression` to `dmd.expression.CommaExp` not allowed in safe code
src/dmd/expression.d(470):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(481): Deprecation: cast from `dmd.expression.Expression` to `dmd.expression.CommaExp` not allowed in safe code
src/dmd/expression.d(481):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(483): Deprecation: cast from `dmd.expression.Expression` to `dmd.expression.CommaExp` not allowed in safe code
src/dmd/expression.d(483):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(486): Deprecation: cast from `dmd.expression.Expression` to `dmd.expression.CommaExp` not allowed in safe code
src/dmd/expression.d(486):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(767): Deprecation: cast from `inout(Expression)` to `inout(IntegerExp)` not allowed in safe code
src/dmd/expression.d(767):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(768): Deprecation: cast from `inout(Expression)` to `inout(ErrorExp)` not allowed in safe code
src/dmd/expression.d(768):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(769): Deprecation: cast from `inout(Expression)` to `inout(VoidInitExp)` not allowed in safe code
src/dmd/expression.d(769):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(770): Deprecation: cast from `inout(Expression)` to `inout(RealExp)` not allowed in safe code
src/dmd/expression.d(770):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(771): Deprecation: cast from `inout(Expression)` to `inout(ComplexExp)` not allowed in safe code
src/dmd/expression.d(771):        No dynamic type information for extern(C++) classes
src/dmd/expression.d(772): Deprecation: cast from `inout(Expression)` to `inout(IdentifierExp)` not allowed in safe code

gmake: *** [Makefile:83: dmd] Error 1
```

**Comment by adamdruppe** [comment]
I think that is fixed on the new master push now

**Comment by whisperzer0** [comment]
Thanks, that built dmd successfully, 

```
Using D host compiler: ldmd2
generated/build dmd
(DC) DMD
Success
```

druntime is now throwing errors.

gmake -j8 druntime 

```
src/core/sys/freebsd/execinfo.d(51): Deprecation: `@safe` function `backtrace` cannot index pointer `buffer`
src/core/sys/freebsd/execinfo.d(51): Deprecation: pointer arithmetic not allowed in @safe functions
src/core/sys/freebsd/execinfo.d(89): Deprecation: pointer arithmetic not allowed in @safe functions
src/core/sys/freebsd/execinfo.d(91): Deprecation: `@safe` function `backtrace_symbols` cannot index pointer `p`
src/core/sys/freebsd/execinfo.d(96): Deprecation: `@safe` function `backtrace_symbols` cannot index pointer `p`
src/core/sys/freebsd/execinfo.d(97): Deprecation: `@safe` function `backtrace_symbols` cannot index pointer `p`
src/core/sys/freebsd/execinfo.d(97): Deprecation: pointer arithmetic not allowed in @safe functions
src/core/sys/freebsd/execinfo.d(126): Deprecation: `@safe` function `backtrace_symbols_fd` cannot index pointer `p`
src/core/sys/freebsd/execinfo.d(51): Deprecation: `@safe` function `backtrace` cannot index pointer `buffer`
src/core/sys/freebsd/execinfo.d(51): Deprecation: pointer arithmetic not allowed in @safe functions
src/core/sys/freebsd/execinfo.d(89): Deprecation: pointer arithmetic not allowed in @safe functions
src/core/sys/freebsd/execinfo.d(91): Deprecation: `@safe` function `backtrace_symbols` cannot index pointer `p`
src/core/sys/freebsd/execinfo.d(96): Deprecation: `@safe` function `backtrace_symbols` cannot index pointer `p`
src/core/sys/freebsd/execinfo.d(97): Deprecation: `@safe` function `backtrace_symbols` cannot index pointer `p`
src/core/sys/freebsd/execinfo.d(97): Deprecation: pointer arithmetic not allowed in @safe functions
src/core/sys/freebsd/execinfo.d(126): Deprecation: `@safe` function `backtrace_symbols_fd` cannot index pointer `p`
gmake[1]: *** [Makefile:422: ../generated/freebsd/release/64/libdruntime.a] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [Makefile:416: ../generated/freebsd/release/64/libdruntime.so.a] Error 1
gmake[1]: Leaving directory '/tmp/opend/druntime'
gmake: *** [Makefile:90: druntime] Error 2
```

**Comment by whisperzer0** [comment]
awesome. dmd compiled with no issues.

ldc is having a few mishaps, one looks easy fixed. 

`/tmp/opend/ldc/gen/declarations.cpp:421:18: error: no member named 'startswith' in 'llvm::StringRef'; did you mean 'starts_with'?
`
but others include:

```
In file included from /tmp/opend/ldc/gen/dcompute/targetCUDA.cpp:21:
/tmp/opend/ldc/./driver/targetmachine.h:69:39: error: no type named 'Level' in namespace 'llvm::CodeGenOpt'
   69 |                     llvm::CodeGenOpt::Level codeGenOptLevel,
      |                     ~~~~~~~~~~~~~~~~~~^
```

So, I'll leave that with you. 

dmd allows me play away anyway -- thank you for your help on this!
feel free to close.

**Comment by adamdruppe** [comment]
for ldc, it *only* supports llvm version 17.0.6. version 18 introduced some breakage, and previous ones ive never tested. but you really gotta get v17 to build it yourself rn.

**Comment by adamdruppe** [comment]
I got it all building on my new freebsd thing. But my notes on that computer aren't online yet lol but it is a fairly small patch. Then a few things:

* the top-level makefile can build dmd and druntime, but for phobos, you have to `cd phobos; gmake`. Can probably be fixed, it is just generic `make` on bsd is not compatible with these gnu makefiles.
* ldc-profgen fails but that's not important, i might as well just remove it from the standard make target. you can ignore that.
* ldc2 build needs the removal of an `-Xlinker --export-dynamic` and the addition of `-lzstd -L/usr/local/bin` in the link command. (the ztd  thing needs to be added on my Slackware Linux box too so i recognized that lol)
* again make sure you  use gmake throughout. also `pkg add llvm17` and `cmake ../ldc -DLLVM_ROOT_DIR=.... whatever it was to llvm17 i forgot.`

the patches for dmd are already up here, druntime was minor, sure you did that yourself, phobos meant removing a gratuitious importc use with inline definitions of malloc/free/calloc, no big deal.

so a few little things, nothing big, and we have a freebsd 14 build. i'll see about making it more turnkey once i get my ssh keys and whatnot on that other computer so i can push the patches online.

**Comment by adamdruppe** [comment]
The new master adds all the little fixes I needed to make it work. So you can `gmake HOST_DMD=path/to/upstream/dmd` and it should succeed when you have llvm17 around, might still need to do that LLVM_ROOT_DIR thing, but i didn't on my last try (but that might just be because something was cached from specifying it the first time).
